#cloud-config
# network-verifier-required-variables=CURL_COMMAND,DELAY
${CACERT_RENDERED}
runcmd:
  - systemctl mask --now serial-getty@ttyS0.service
  - dmesg -D
  - echo "${USERDATA_BEGIN}" >/dev/ttyS0
  - export http_proxy=${HTTP_PROXY} https_proxy=${HTTPS_PROXY} no_proxy="${NO_PROXY}"
  - ${CURL_COMMAND} 2>/dev/ttyS0
  - echo "${USERDATA_END}" >/dev/ttyS0
power_state:
  delay: ${DELAY}
  mode: poweroff
  message: Auto-terminating instance due to timeout
  timeout: 300
